site_name: Solo
site_author: SoloKeys
site_description: 'Documentation for all SoloKeys projects'
repo_name: 'solokeys/docs'
repo_url: 'https://github.com/solokeys/docs'
copyright: 'Copyright &copy; 2018 SoloKeys. Licensed under CC BY-SA 4.0'

theme:
  name: material
  logo: 'images/logo-black_on_transparent.svg'
